### ISSUE TITLE
Binary wheels

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/ssh-python#2]
Make binary wheels for all platforms.

**Comment by pkittenis** [comment]
As a status update:

* OSX and Linux wheels are done.
* Windows wheels done with the exception of Python 2.7 which is a blocker to complete this.

The issue there is libssh does not build on VC9 as it lacks C99 support. VC9 is required to build python 2.7 extensions on windows. There are a couple options to resolve this:

* Hack libssh code to build on VC9 - not a reasonable course of action and would require extensive changes to code.
* Downgrade libssh version to one that is VC9 compatible (<0.6.0). This requires changes to the bindings to support the earlier version. This is mostly taking stuff out.
* Don't ship Windows Python 2.7 wheels - this means no support for Python 2 on Windows.

Leaning towards downgrading libssh for the Windows Python 2.7 build alone, with a note saying 'use Python 3 on Windows'. If this proves too difficult, will end up skipping Python 2 on Windows.

See [this branch for changes](https://github.com/ParallelSSH/ssh-python/tree/windows_wheels).

**Comment by cryptomilk** [comment]
I would just go with python3 on Windows :-)

**Comment by pkittenis** [comment]
Added OSX wheels for 10.14 and 10.15 on Python 3.8
Added Windows 64 bit wheels for python 3.6/3.7/3.8
