### ISSUE TITLE
Update to libssh 0.9.5

### ISSUE THREAD

**Issue by enkore** [ParallelSSH/ssh-python#23]
libssh 0.9.x up to 0.9.5 contains a bug where ssh_channel_read() will sometimes incorrectly return SSH_ERROR. This happens a lot when executing short-lived programs that produce no or little output.

- libssh bug: https://bugs.libssh.org/T231
- libssh change: https://gitlab.com/libssh/libssh-mirror/-/commit/750e4f3f9d3ec879929801d65a500ec3ad84ff67

(eref 42d478fb6976)

**Comment by pkittenis** [comment]
Thanks for the interest and report. That is a pretty easy change if anyone would like to make a PR.
