### ISSUE TITLE
Higher level API?

### ISSUE THREAD

**Issue by jerlich** [ParallelSSH/ssh-python#38]
Seems it would be useful to have an API that hides all the socket stuff. like

```python
s = sshSession(hostname=hostname) # Use .ssh/config
s = sshSession(user=user, pass=pass, host=host) 
```

**Comment by pkittenis** [comment]
See [parallel-ssh](https://parallel-ssh.readthedocs.io/en/latest/advanced.html#ssh-python-libssh-client).

Out of scope for this project.
