### ISSUE TITLE
[Feature Request] Shorter and quicker functions

### ISSUE THREAD

**Issue by nsde** [ParallelSSH/ssh-python#39]
Why does this library take 33 lines just for sending an command? Please make easier to use! Thanks.

Perfect would be:

```py
import ssh

with ssh.Connection('123.456.789', 'root', 22) as console:
    output = console.run('echo Hey')
print(output)
```

That'd make this library sooo much more efficient :)

**Comment by pkittenis** [comment]
Use [parallel-ssh](https://parallel-ssh.readthedocs.io/en/latest/quickstart.html).

Out of scope for this library.
