### ISSUE TITLE
CI: Remove Python 3.6, add 3.9 and 3.10

### ISSUE THREAD

**Issue by enkore** [ParallelSSH/ssh-python#46]

**Comment by pkittenis** [comment]
Might be better to remove 3.7 and leave 3.6 as the oldest supported Python 3 version.

**Comment by enkore** [comment]
Fixed by [3f838cb](https://github.com/ParallelSSH/ssh-python/commit/3f838cb5ba8a40b5316d7791b59afc922f934914)
