### ISSUE TITLE
Versions of libssh other than the one embedded in this project are not supported

### ISSUE THREAD

**Issue by adelton** [ParallelSSH/ssh-python#5]
Hello,

I'm interested in your work on ssh-python. However, the use of embedded libssh is a blocker for us because we need to be able to build the code against the libssh/libssh-devel packaged in the operating system. For example, Fedora 29 currently ships libssh 0.8.7, and we need to be able to build and test with that.

Of course, I understand your position from https://github.com/ParallelSSH/ssh-python/issues/1 about not supporting older version of libssh. But that should be possible to ensure by simply requiring a particular minimal version of the library.

I wonder if you'd be willing to remove the embedded libssh copy and use externally available header files / library, in rather short term.

Thank you,

Jan

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. There is already support for building against system libssh - use `SYSTEM_LIBSSH=1` env variable. It does not, nor do I have any interest in, supporting versions other than the one embedded. So for building against system library, it is builder responsibility to have a new enough version to be compatible. Anything above 0.8 should be ok.
