### ISSUE TITLE
Tag typo 03.0

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [ParallelSSH/ssh-python#58]
Hello, I'm having issues with an automated update script because it wan'ts to update my ssh-python to version 03.0 as 03.0 is bigger than 0.10.0. I guess it's a typo but it would be great if you could remove or rename this tag https://github.com/ParallelSSH/ssh-python/releases/tag/03.0 to avoid anyone having this same issues and lose time on that.

**Comment by pkittenis** [comment]
Thanks for the interest and report.

There is no 03.0 release published on PyPi - https://pypi.org/manage/project/ssh-python/releases/

Tags cannot be removed from a repository. Best to use pip and PyPi for upgrading.
