### ISSUE TITLE
python 3.11 win10 x64 support

### ISSUE THREAD

**Issue by irvinren** [ParallelSSH/ssh-python#62]
Failed to compile on win10 x64,

ssh-python>python setup.py build
Library dirs: ['/usr/local/lib'], runtime dirs: None, include: ['./local/include', './libssh/include']
Cython arguments: {'cython_directives': {'embedsignature': True, 'boundscheck': False, 'optimize.use_switch': True, 'wraparound': False, 'language_level': 2}, 'cython_compile_time_env': {'ON_WINDOWS': True}}
Windows platform: True, Python major version: 3.
running build
running build_py
warning: cmd_build_py: byte-compiling is disabled, skipping.

running build_ext
skipping 'ssh\callbacks.c' Cython extension (up-to-date)
skipping 'ssh\channel.c' Cython extension (up-to-date)
skipping 'ssh\connector.c' Cython extension (up-to-date)
skipping 'ssh\error_codes.c' Cython extension (up-to-date)
skipping 'ssh\event.c' Cython extension (up-to-date)
skipping 'ssh\exceptions.c' Cython extension (up-to-date)
skipping 'ssh\key.c' Cython extension (up-to-date)
skipping 'ssh\keytypes.c' Cython extension (up-to-date)
skipping 'ssh\options.c' Cython extension (up-to-date)
skipping 'ssh\scp.c' Cython extension (up-to-date)
skipping 'ssh\session.c' Cython extension (up-to-date)
skipping 'ssh\sftp.c' Cython extension (up-to-date)
skipping 'ssh\sftp_attributes.c' Cython extension (up-to-date)
skipping 'ssh\sftp_handles.c' Cython extension (up-to-date)
skipping 'ssh\sftp_statvfs.c' Cython extension (up-to-date)
skipping 'ssh\utils.c' Cython extension (up-to-date)
building 'ssh.callbacks' extension
creating build\temp.win-amd64-cpython-311
creating build\temp.win-amd64-cpython-311\Release
creating build\temp.win-amd64-cpython-311\Release\ssh
"E:\Microsoft Visual Studio\2019\Communiity\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I./local/include -I./libssh/includ
e -IC:\Users\brigh\.virtualenvs\shared_atomic_private311-B_vIHjcf\include -ID:\Python311\include -ID:\Python311\Include "-IE:\Microsoft Visual Studio\2019\Communiity
\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IE:\Microsoft Visual Studio\2019\Communiity\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.20348.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um"
 "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt" /Tcssh\callbacks.c /F
obuild\temp.win-amd64-cpython-311\Release\ssh\callbacks.obj
callbacks.c
./libssh/include\libssh/libssh.h(24): fatal error C1083: Cannot open include file: 'libssh/libssh_version.h': No such file or directory
error: command 'E:\\Microsoft Visual Studio\\2019\\Communiity\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by irvinren** [comment]
any update?

**Comment by enkore** [comment]
It does work in CI (see #63), so try cross-checking what you did and have installed with how the CI build script works.

Or you could try the cpy3.11 wheel built in #63, it *should* work, though I haven't tried it yet: https://ci.appveyor.com/api/buildjobs/q75iuvx14147dapl/artifacts/ssh_python-0.10.0_5_ga007ce5-cp311-cp311-win_amd64.whl

**Comment by pkittenis** [comment]
Thanks for the interest.

Please follow [the instructions for building from source](https://ssh-python.readthedocs.io/en/latest/installation.html#building-on-windows).

Suggest to wait for binary wheels for 3.11 on Windows to be published.
