### ISSUE TITLE
Windows C Runtime issues

### ISSUE THREAD

**Issue by enkore** [ParallelSSH/ssh-python#64]
Currently we're blanket-copying all VCRTs installed on the build VM into the wheel, this is mostly unnecessary bloat because they're all unused except for two libraries (MSVCRT120 and VCRUNTIME140). IIRC it used to be the case that MS didn't allow redistributing the individual files and required use of the vcredist installer, [but that seems to be officially allowed nowadays](https://learn.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files?view=msvc-170#install-individual-redistributable-files). I think ideally we would build all our stuff linked against the UCRT, that way we don't have to include any C runtimes (either as DLLs or statically linked into each DLL).

(Also I think the files are incomplete, because most of our DLLs also import from the "fractionalized" api-ms-xxxxx.dll runtimes)

**Comment by pkittenis** [comment]
Yes, historically the project blanket copied all MSVCRT*.dlls to make it compatible with the multiple Visual Studio versions that were previously used.

Now we have standardised on Visual Studio 19 and only use one version to build all releases, the single runtimes used in that version can be bundled only.

**Comment by enkore** [comment]
I'll try to fit this in early next week and then we have a nice package for another release (Python 3.11 support, ARM wheels, another round of wheel size reductions, updated libssh).
